apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  revisionHistoryLimit: 2 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: admin-server
          image: "{{ .Values.image.adminServer.repository }}:{{ .Values.image.adminServer.tag }}"
          ports:
            - containerPort: {{ .Values.service.adminServer.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_APPLICATION_NAME
              value: admin-server
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: admin-server:${HOSTNAME}
            - name: CONFIG_SERVER_URL
              value: http://config-server:{{ .Values.service.configServer.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - name: http
      port: {{ .Values.service.adminServer.port }}
      targetPort: {{ .Values.service.adminServer.port }}
      nodePort: {{ .Values.service.adminServer.nodePort }}
  type: NodePort

