apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: {{ .Release.Namespace }}
spec:
  {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: api-gateway-allow
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: api-gateway
  action: ALLOW
  rules:
  - {} # Allow all traffic (public entry point)
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: config-server-allow
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: config-server
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["{{ .Release.Namespace }}"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: customers-service-allow
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: customers-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/api-gateway"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: visits-service-allow
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: visits-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/api-gateway"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: vets-service-allow
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: vets-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/api-gateway"]
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/genai-service"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: genai-service-allow
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: genai-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/api-gateway"]
