apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: customers-service
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: customers-service
      containers:
        - name: customers-service
          image: "{{ .Values.image.customersService.repository }}:{{ .Values.image.customersService.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.customersService.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_ZIPKIN_TRACING_ENDPOINT
              value: http://tracing-server:9411/api/v2/spans
            - name: SPRING_APPLICATION_NAME
              value: customers-service
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: ${spring.application.name}:${random.uuid}
            - name: CONFIG_SERVER_URL
              value: http://config-server:{{ .Values.service.configServer.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers-service
  ports:
    - name: http
      port: {{ .Values.service.customersService.port }}
      targetPort: {{ .Values.service.customersService.port }}
