apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default-mtls
  namespace: {{ .Release.Namespace }}
spec:
  host: "*"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
