# DestinationRule with wildcard host (*) is not recommended
# mTLS is already configured via PeerAuthentication
# If you need specific traffic policies for services, create individual DestinationRules
#
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default-mtls
  namespace: {{ .Release.Namespace }}
spec:
  host: "*"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      http:
        http1MaxPendingRequests: 1024
