apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default-mtls
  namespace: {{ .Release.Namespace }}
spec:
  host: "*.{{ .Release.Namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
