apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: api-gateway-external
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: api-gateway
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: discovery-server-permissive
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: discovery-server
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: admin-server-external
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: admin-server
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: config-server-external
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: config-server
  mtls:
    mode: PERMISSIVE
