apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
  portLevelMtls:
    8080:
      mode: PERMISSIVE # API Gateway
    9090:
      mode: PERMISSIVE # Admin Server
    8888:
      mode: PERMISSIVE # Config Server
