apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customers-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vets-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: visits-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: genai-service
