apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: vets-service
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: vets-service
          image: "{{ .Values.image.vetsService.repository }}:{{ .Values.image.vetsService.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.vetsService.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_ZIPKIN_TRACING_ENDPOINT
              value: http://tracing-server:9411/api/v2/spans
            - name: SPRING_APPLICATION_NAME
              value: vets-service
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: ${spring.application.name}:${random.uuid}
            - name: SPRING_CACHE_TTL
              value: "60"
            - name: SPRING_CACHE_HEAP_SIZE
              value: "100"
            - name: CONFIG_SERVER_URL
              value: http://config-server:{{ .Values.service.configServer.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  selector:
    app: vets-service
  ports:
    - name: http
      port: {{ .Values.service.vetsService.port }}
      targetPort: {{ .Values.service.vetsService.port }}
